-- THE BAD ANSWER
-- --------------
SELECT COUNT(CITY)
  FROM (
       SELECT CITY, COUNT(CITY) AS QUANT
         FROM STATION
        GROUP BY CITY
       ) A
 WHERE QUANT > 1


-- THE CORRECT ANSWER
-- ------------------
DECLARE @TOTAL INT, @DISTINCT INT;
SELECT @TOTAL = ( SELECT COUNT(CITY) FROM STATION) ;
SELECT @DISTINCT = ( SELECT COUNT(DISTINCT CITY) FROM STATION) ;
SELECT @TOTAL - @DISTINCT;


-- THE BEST ANSWER
-- ---------------
SELECT COUNT(CITY) - COUNT(DISTINCT CITY) FROM STATION

